apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: vite-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
