apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: backend
  labels:
    app: spring-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: andyrews/clark-site-backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.postgres.svc.cluster.local:5432/personalwebsite
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: $Qlbench3r20
