apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30023
  type: NodePort
