apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: personalwebsite
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: $Qlbench3r20